name: Deploy to Azure

on: #event to trigger the workflow
  push:
    branches:
      - main 

jobs:
  app-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
          allow-no-subscriptions: true
        #with:
        # client-id: ${{ secrets.AZURE_CLIENT_ID }}
        # tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        # subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        
    #- name: Set Default Subscription
    #   run: az account set --subscription <subscription-id>

      - name: Azure Account List
        run: az account list --output table
        
      - name: Azure group list
        run: az group list --query "[].name" --output table
          
      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'Dalley App'  # Replace with your Azure App Service name
          package: .  # current directory
